version: '3'

services:
  mongodb:
    volumes:
      - './mongodb/mongodb:/data/db'
    container_name: mongodb
    image: mongo
    network_mode: 'host'

  frontend:
    build:
      context: client/.
    container_name: frontend
    network_mode: 'host'
    depends_on:
      - backend

  backend:
    build:
      context: .
    container_name: backend
    restart: always
    depends_on:
      - mongodb
    network_mode: 'host'
